"""
utils/pdf_report.py
────────────────────
Generates a downloadable PDF report of the ATS screening results.
Uses fpdf2 for lightweight, dependency-free PDF generation.
"""

import io
from typing import Optional


def generate_pdf_report(
    candidate_name: str,
    total_score: int,
    grade: str,
    extraction: dict,
    matching: dict,
    scoring: dict,
    recommendation: str,
    ats_tips: str = "",
    keyword_cloud_image: Optional[bytes] = None,
) -> io.BytesIO:
    """
    Generate a professional PDF report of the ATS screening results.

    Returns:
        BytesIO buffer containing the PDF.
    """
    from fpdf import FPDF
    import re

    def _safe_text(text: str) -> str:
        """Convert fancy quotes/emojis to basic ascii so fpdf Helvetica doesn't crash."""
        if not text:
            return ""
        # Replace common unicode dashes and box drawing with hyphens
        text = re.sub(r'[—–━]', '-', text)
        # Drop non-latin characters (like emojis)
        return text.encode('latin-1', errors='ignore').decode('latin-1')

    class ATSReport(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 18)
            self.set_text_color(88, 166, 255)  # #58a6ff
            self.cell(0, 12, "ATS Resume Screener Report", align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(48, 54, 61)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(139, 148, 158)
            self.cell(0, 10, f"Page {self.page_no()} | Generated by ATS Resume Screener | github.com/AbhishekKharat04", align="C")

    pdf = ATSReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Candidate Header ─────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(230, 237, 243)
    pdf.cell(0, 10, f"Candidate: {candidate_name}", new_x="LMARGIN", new_y="NEXT")

    # Score + Grade
    pdf.set_font("Helvetica", "B", 28)
    if total_score >= 85:
        pdf.set_text_color(63, 185, 80)
    elif total_score >= 70:
        pdf.set_text_color(88, 166, 255)
    elif total_score >= 50:
        pdf.set_text_color(210, 153, 34)
    else:
        pdf.set_text_color(248, 81, 73)

    pdf.cell(0, 16, f"ATS Score: {total_score}/100  |  Grade: {grade}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── Score Breakdown ──────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(88, 166, 255)
    pdf.cell(0, 8, "SCORE BREAKDOWN", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(205, 217, 229)
    skills_score = scoring.get("skills_score", 0)
    exp_score = scoring.get("experience_score", 0)
    tools_score = scoring.get("tools_score", 0)
    pdf.cell(0, 6, f"  Skills Match:     {skills_score}/50  (50% weight)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"  Experience:       {exp_score}/30  (30% weight)", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"  Tools Match:      {tools_score}/20  (20% weight)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── Matched Skills ───────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(63, 185, 80)
    pdf.cell(0, 8, "MATCHED SKILLS & TOOLS", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(205, 217, 229)
    matched_s = matching.get("matched_skills", [])
    matched_t = matching.get("matched_tools", [])
    if matched_s:
        pdf.cell(0, 6, f"  Skills: {', '.join(matched_s)}", new_x="LMARGIN", new_y="NEXT")
    if matched_t:
        pdf.cell(0, 6, f"  Tools:  {', '.join(matched_t)}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Missing Skills ───────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(248, 81, 73)
    pdf.cell(0, 8, "MISSING SKILLS & TOOLS", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(205, 217, 229)
    missing_s = matching.get("missing_skills", [])
    missing_t = matching.get("missing_tools", [])
    if missing_s:
        pdf.cell(0, 6, f"  Skills: {', '.join(missing_s)}", new_x="LMARGIN", new_y="NEXT")
    if missing_t:
        pdf.cell(0, 6, f"  Tools:  {', '.join(missing_t)}", new_x="LMARGIN", new_y="NEXT")
    if not missing_s and not missing_t:
        pdf.cell(0, 6, "  No critical gaps!", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # ── Keyword Cloud ────────────────────────────────────────────────────
    if keyword_cloud_image:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(88, 166, 255)
        pdf.cell(0, 8, "KEYWORD CLOUD", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        import tempfile, os
        tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        tmp.write(keyword_cloud_image)
        tmp.close()
        try:
            pdf.image(tmp.name, x=15, w=180)
        finally:
            os.unlink(tmp.name)
        pdf.ln(5)

    # ── Recommendation ───────────────────────────────────────────────────
    if recommendation:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(88, 166, 255)
        pdf.cell(0, 8, "HIRING RECOMMENDATION", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(205, 217, 229)
        # Multi-cell for wrapping long text
        for line in recommendation.split("\n"):
            pdf.multi_cell(0, 5, _safe_text(line))
        pdf.ln(5)

    # ── ATS Improvement Tips ─────────────────────────────────────────────
    if ats_tips:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(88, 166, 255)
        pdf.cell(0, 8, "ATS IMPROVEMENT TIPS", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(205, 217, 229)
        for line in ats_tips.split("\n"):
            pdf.multi_cell(0, 5, _safe_text(line))

    # Output
    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf
